language: c
sudo: required
dist: trusty
compiler:
   - gcc
   - clang
before_install:
   - sudo apt-get update -qq
   - sudo apt-get install -y libsdl2-2.0-0 libsdl2-image-2.0-0 libgl1-mesa-dri libxml2 libfreetype6 libpng12-0 libopenal1 libvorbis0a libzip2 build-essential automake libsdl2-dev libsdl2-image-dev libgl1-mesa-dev libxml2-dev libfreetype6-dev libpng12-dev libopenal-dev libvorbis-dev binutils-dev libzip-dev libiberty-dev libluajit-5.1-dev
script: ./autogen.sh && ./configure && make
