language: c

matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      sudo: false

addons:
  apt:
    packages:
      - build-essential
      - luarocks

before_install:
  - |
    # Install LuaRocks packages
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      luarocks install --local ldoc
    fi

script:
  - |
    # Build Naev Lua docs
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export PATH="$PATH:$HOME/.luarocks/bin"
      (cd docs && ./ldoc.sh)
    fi

deploy:
  - provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      condition: "$TRAVIS_OS_NAME = linux"
