
#on:
#  schedule:
#    - cron: '0 0 * * *'
# on:  
 # push:
 #   # Sequence of patterns matched against refs/tags
 #   tags:
 #     - 'naev-*' # Push events to matching naev-*

on: [push, pull_request]

name: Nightly Release

jobs:
  win32:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: Setup MINGW32 Environment
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        update: true
        install: mingw-w64-i686-libtool mingw-w64-i686-toolchain mingw-w64-i686-gcc mingw-w64-i686-SDL2 mingw-w64-i686-SDL2_mixer mingw-w64-i686-SDL2_image mingw-w64-i686-libxml2 mingw-w64-i686-libpng mingw-w64-i686-openal mingw-w64-i686-libvorbis mingw-w64-i686-binutils mingw-w64-i686-freetype mingw-w64-i686-libzip mingw-w64-i686-gettext mingw-w64-i686-luajit mingw-w64-i686-nsis libtool autoconf autoconf-archive automake automake-wrapper git gettext pkgconfig make intltool itstool zip unzip
    
    - name: Checkout Naev Repository 
      uses: actions/checkout@v2

    - name: Build Naev on Win32
      run: |
        ./autogen.sh
        ./configure  --disable-debug
        make -j$(nproc --all)
      env:
        CFLAGS: "-O3"

    - name: Build Windows Installer
      run: ./extras/windows/packageWindows.sh

    - name: Upload Release Asset
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "nightly"
        prerelease: true
        title: "Nightly Build"
        files: |
          ${{ github.workspace }}/extras/windows/installer/naev-${{ github.sha }}-win32.exe

  win64:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: Setup MINGW64 Environment
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: mingw-w64-x86_64-libtool mingw-w64-x86_64-toolchain mingw-w64-x86_64-gcc mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL2_mixer mingw-w64-x86_64-SDL2_image mingw-w64-x86_64-libxml2 mingw-w64-x86_64-libpng mingw-w64-x86_64-openal mingw-w64-x86_64-libvorbis mingw-w64-x86_64-binutils mingw-w64-x86_64-freetype mingw-w64-x86_64-libzip mingw-w64-x86_64-gettext mingw-w64-x86_64-luajit mingw-w64-x86_64-nsis libtool autoconf autoconf-archive automake automake-wrapper git gettext pkgconfig make intltool itstool zip unzip

    - name: Checkout Naev Repository 
      uses: actions/checkout@v2

    - name: Build Naev on Win64
      run: |
        ./autogen.sh
        ./configure --disable-debug
        make -j$(nproc --all)
      env:
        CFLAGS: "-O3"

    - name: Build Windows Installer
      run: ./extras/windows/packageWindows.sh

    - name: Upload Release Asset
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "nightly"
        prerelease: true
        title: "Nightly Build"
        files: |
          ${{ github.workspace }}/extras/windows/installer/naev-${{ github.sha }}-win64.exe

  lin64:
    runs-on: ubuntu-20.04

    steps:
    - name: Update APT Cache
      run: |
        sudo apt-get update

    - name: Install Build Dependencies
      run: |
        sudo apt-get install \
          build-essential \
          automake \
          autoconf-archive \
          libsdl2-dev \
          libsdl2-mixer-dev \
          libsdl2-image-dev \
          libgl1-mesa-dev \
          libglu1-mesa-dev \
          libxml2-dev \
          libfontconfig1-dev \
          libfreetype6-dev \
          libpng-dev \
          libopenal-dev \
          libvorbis-dev \
          libzip-dev \
          libiberty-dev \
          libluajit-5.1-dev \
          gettext \
          autopoint \
          intltool \
          itstool

    - name: Checkout Naev Repository 
      uses: actions/checkout@v2

    - name: Build Naev on Linux64
      run: |
        ./autogen.sh
        ./configure
        make -j$(nproc --all)
      env:
        CFLAGS: "-O3"

    - name: Package Linux64 Release
      run: |
        mv src/naev src/naev-${{ github.sha }}-linux-x86-64
        tar -czvf naev-${{ github.sha }}-linux-x86-64.tar.gz src/naev-${{ github.sha }}-linux-x86-64

    - name: Upload Release Asset
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "nightly"
        prerelease: true
        title: "Nightly Build"
        files: |
          ${{ github.workspace }}/naev-${{ github.sha }}-linux-x86-64.tar.gz

  macos:
    runs-on: macos-latest

    steps:
    - name: Update Homebrew Cache
      run: |
        brew update

    - name: Install Additional Build Dependencies
      run: |
        brew install \
          automake \
          autoconf-archive \
          pkg-config \
          fontconfig \
          luajit \
          intltool \
          itstool \
          sdl2 \
          sdl2_mixer \
          sdl2_image \
          openal-soft
          
    - name: Remove Homebrew Perl
      run: |
        brew uninstall --ignore-dependencies perl
        
    - name: Checkout Naev Repository 
      uses: actions/checkout@v2

    - name: Build Naev on MacOS
      run: |
        # PKGCONFIG configuration for OpenAL
        export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/opt/openal-soft/lib/pkgconfig"
        
        ./autogen.sh
        ./configure
        make -j$(sysctl -n hw.logicalcpu)
      env:
        CFLAGS: "-O3 -mmacosx-version-min=10.7"
    
    - name: Package MacOS Release
      run: |
        ./extras/macos/bundle.sh
        zip naev-${{ github.sha }}-macos Naev.app/

    - name: Upload Release Asset
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "nightly"
        prerelease: true
        title: "Nightly Build"
        files: |
          ${{ github.workspace }}/naev-${{ github.sha }}-macos.zip

  ndata:
      runs-on: ubuntu-latest

      steps:
      - name: Update APT Cache
        run: |
          sudo apt-get update

      - name: Install Build Dependencies
        run: |
          sudo apt-get install \
            build-essential \
            automake \
            autoconf-archive \
            libsdl2-dev \
            libsdl2-mixer-dev \
            libsdl2-image-dev \
            libgl1-mesa-dev \
            libxml2-dev \
            libfontconfig1-dev \
            libfreetype6-dev \
            libpng-dev \
            libopenal-dev \
            libvorbis-dev \
            binutils-dev \
            libzip-dev \
            libiberty-dev \
            libluajit-5.1-dev \
            gettext \
            autopoint \
            intltool \
            itstool

      - name: Checkout Naev Repository 
        uses: actions/checkout@v2

      - name: Build Naev on Linux64
        run: |
          ./autogen.sh
          ./configure
          make "ndata.zip"
          mv ndata.zip ndata-${{ github.sha }}.zip

      - name: Upload Release Asset
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: true
          title: "Nightly Build"
          files: |
            ${{ github.workspace }}/ndata-${{ github.sha }}.zip
